services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ami_integration_project
      POSTGRES_USER: ami
      POSTGRES_PASSWORD: Ami@2025
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    restart: always

  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis_broker
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: "false"
    ports:
      - "8161:8161" # Porta do console de administração web
      - "61616:61616" # Porta do protocolo OpenWire/Core
      - "5672:5672" # Porta do protocolo AMQP
      - "1883:1883" # Porta do protocolo MQTT
    volumes:
      - artemis_data:/var/lib/artemis-instance
    restart: always

volumes:
  postgres_data:
  redis_data:
  artemis_data:
