services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: trainee_integration_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: n00b13
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    restart: always

  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis_broker
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
    ports:
      - "61616:61616" # Porta do protocolo OpenWire/Core
      - "8161:8161"   # Console web
    volumes:
      - artemis_data:/var/lib/artemis-instance
    restart: always

  standard-business:
    image: 10.160.0.21:5000/trainee-standard-business:latest
    container_name: business
    environment:
      BROKER_URL: artemis
      BROKER_PORT: 61616
      BROKER_USER: artemis
      BROKER_PASSWORD: artemis
      REDIS_HOST: redis_server
      REDIS_PORT: 6379
      DATASOURCE_JDBC: jdbc:postgresql://postgres_db:5432/trainee_integration_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: n00b13
    ports:
      - "8081:8080"
    volumes:
      - business_data:/data
    restart: always

  cronjob:
    image: 10.160.0.21:5000/trainee-cronjob:latest
    container_name: cronjob
    environment:
      BROKER_URL: artemis
      BROKER_PORT: 61616
      BROKER_USER: artemis
      BROKER_PASSWORD: artemis
      REDIS_HOST: redis_server
      REDIS_PORT: 6379
      DATASOURCE_JDBC: jdbc:postgresql://postgres_db:5432/trainee_integration_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: n00b13
    ports:
      - "8082:8080"
    volumes:
      - cronjob_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
  artemis_data:
  business_data:
  cronjob_data: